In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr = np.array([2,3,4,5,6,7,8])
print(arr)
print(arr.ndim)
print("Shape :",arr.shape)


[2 3 4 5 6 7 8]
1
Shape : (7,)


In [ ]:
arr=np.array(["a","b","c"])
print(arr)
print(arr.ndim)
print(arr.itemsize)

['a' 'b' 'c']
1
4


In [ ]:
print(arr.dtype)

<U1


In [ ]:
arr=np.random.randn(2,2)
print(arr)

[[-0.86702738  1.0671922 ]
 [-0.83861306  1.11753626]]


In [ ]:
arr=np.random.randint(1,10,(2,3))
print(arr)
print(arr.dtype)

[[2 8 4]
 [2 9 8]]
int64


In [ ]:
#2. Create an array of even numbers from 2 to 50.
arr =np.array([i for i in range(2,50) if i%2==0])
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
#3. Create an array of odd numbers from 1 to 99.
arr =np.array([i for i in range(1,99) if i%2!=0])
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97]


In [ ]:
#4. Create a 3×3 array of zeros.
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#5. Create a 4×4 array of ones.
arr=np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#6. Create a 5×5 identity matrix.
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#7. Create a diagonal matrix with values 1 to 5.
arr=np.diag((1,2,3,4,5))
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
#8. Generate a random array of 10 integers.
arr=np.random.randint(1,10,(2,3))
print(arr)

[[4 6 8]
 [5 8 6]]


In [ ]:
#9. Generate a 3×3 random float matrix.
arr=np.random.uniform(1,10,(2,3))
print(arr)

[[4.54025089 8.72345571 7.89554683]
 [5.02017311 5.47350738 8.95132286]]


In [ ]:
#10. Find shape of a NumPy array.
print(arr.shape)

(2, 3)


In [ ]:
#11. Find dimensions of an array.
print(arr.ndim)

2


In [ ]:
#12. Find datatype of array elements.
print(arr.dtype)

float64


In [ ]:
#13. Find size of array.
print(arr.size)

6


In [ ]:
#14. Find itemsize of array.
print(arr.itemsize)

8


In [ ]:
#15. Find total bytes consumed by array.
print(arr.itemsize * arr.size)

48


In [ ]:
#16. Reshape 1D array into 2D array.
arr=np.arange(8)
print(arr)
d=arr.reshape(2,4)
print(d)
print(d.ndim)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
2


In [ ]:
#17. Reshape array into 3D array.
arr=np.arange(9)
d=arr.reshape(3,3)
print(d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#18. Use reshape with -1.
arr=np.arange(12)
d=arr.reshape(3,-1)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#19. Flatten a matrix using flatten().
arr=np.random.randint(1,10,(2,3))
print(arr)
arr.flatten()

[[7 5 3]
 [7 2 7]]


array([7, 5, 3, 7, 2, 7])

In [ ]:
#20. Flatten a matrix using ravel().

ra=arr.ravel()
print(ra)

[7 5 3 7 2 7]


In [ ]:
#21. Transpose a matrix.
arr=np.random.randint(1,10,(2,3))
print(arr)
arr.T


[[5 3 5]
 [7 6 9]]


array([[5, 7],
       [3, 6],
       [5, 9]])

In [ ]:
#22. Expand dimensions row-wise.
arr=np.random.randint(1,10,(1,7))
print(arr)

[[4 9 8 1 7 8 8]]


In [ ]:
#23. Expand dimensions column-wise.
arr=np.random.randint(1,10,(7,1))
print(arr)

[[3]
 [7]
 [2]
 [2]
 [7]
 [4]
 [7]]


In [ ]:
#24. Remove single dimension using squeeze().
squeezed = np.squeeze(arr)
print(squeezed.shape)
print(squeezed)

(7,)
[3 7 2 2 7 4 7]


In [ ]:
#25. Access first element of array.
arr[0]

array([3])

In [ ]:
#26. Access last element using negative indexing.
arr[: : -1]
arr[-1]

array([7])

In [ ]:
#27. Access middle element of array.
n=len(arr )//2
print(arr[n])

[2]


In [ ]:
#28. Print first row of matrix.
arr=np.array([[1,2,3],
     [2,3,5],
     [7,8,9]])
print(arr)
print(arr[0,0:4])

[[1 2 3]
 [2 3 5]
 [7 8 9]]
[1 2 3]


In [ ]:
#29. Print last column of matrix.
arr=np.array([[1,2,3],
     [2,3,5],
     [7,8,9]])
print(arr[0:3,2])

[3 5 9]


In [ ]:
#30. Print second matrix from 3D array.
arr=np.array([[[1,2,3],
     [2,3,5]],
     [[7,8,9],
      [9,8,7]]])
print(arr.ndim)
print(arr[1,0:2,0:3])

3
[[7 8 9]
 [9 8 7]]


In [ ]:
#31. Slice first 5 elements.
arr=np.arange(8)
print(arr)
print(arr[1:6])

[0 1 2 3 4 5 6 7]
[1 2 3 4 5]


In [ ]:
#32. Slice elements from index 2 to 8.
arr=np.arange(15)
print(arr)
print(arr[2:9])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[2 3 4 5 6 7 8]


In [ ]:
#33. Print every second element.
print(arr[2:15:2])

[ 2  4  6  8 10 12 14]


In [ ]:
#34. Reverse array using slicing.
print(arr[15: :-1])

[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [ ]:
#35. Print alternate rows from matrix.
arr=np.arange(12).reshape(3,4)
print(arr)
print(arr[: :2, : ])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [ ]:
#36. Print alternate columns from matrix.
arr=np.arange(12).reshape(3,4)
print(arr)
print(arr[ : ,: : 2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [ ]:
#37. Extract first 2 rows and 3 columns.
arr=np.arange(12).reshape(3,4)
print(arr)
print(arr[ 0:2,0:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2]
 [4 5 6]]


In [ ]:
#38. Extract diagonal elements from matrix.
print(np.diag(arr))

[ 0  5 10]


In [ ]:
#39. Extract last row from every matrix in 3D array.
arr=np.array([[[1,2,3],
     [2,3,5]],
     [[7,8,9],
      [9,8,7]]])
print(arr[[0,1],0:2,2:3])

[[[3]
  [5]]

 [[9]
  [7]]]


In [ ]:
#40. Extract first column from every matrix.
print(arr[[0,1],0:2,0:1])

[[[1]
  [2]]

 [[7]
  [9]]]


In [ ]:
#41. Replace all even numbers with 0.
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    if arr[i,j]%2==0:
      arr[i,j]=0
print(arr)



[[0 0 0]
 [0 9 0]]


In [ ]:
#42. Replace all odd numbers with -1.
arr=np.array([[1,2,3],
     [2,3,5],
     [7,8,9]])
for i in range(arr.shape[0]):
  for j in range(arr.shape[0]):
    if arr[i,j]%2!=0:
      arr[i,j]=-1
print(arr)


[[-1  2 -1]
 [ 2 -1 -1]
 [-1  8 -1]]


In [ ]:
#43. Replace negative numbers with 0.
for i in range(arr.shape[0]):
  for j in range(arr.shape[0]):
    if arr[i,j]<0:
      arr[i,j]=0
print(arr)

[[0 2 0]
 [2 0 0]
 [0 8 0]]


In [ ]:
#44. Replace diagonal elements with 9.
arr=np.array([[1,2,3],
     [2,3,5],
     [7,8,9]])
np.fill_diagonal(arr,9)
print(arr)


[[9 2 3]
 [2 9 5]
 [7 8 9]]


In [ ]:
#45. Swap first and last rows.
arr=np.array([[1,2,3],
     [2,3,5],
     [7,8,9]])
arr[[0,-1]]=arr[[-1,0]]
print(arr)

[[7 8 9]
 [2 3 5]
 [1 2 3]]


In [ ]:
#44. Replace diagonal elements with 9.
arr=np.eye(3,3)
np.fill_diagonal(arr,9)
print(arr)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


In [ ]:
#46. Swap first and last columns.
arr=np.array([[1,2,3],
     [2,3,5],
     [7,8,9]])
arr[:,[0,-1]]=arr[: ,[-1,0]]
print(arr)

NameError: name 'np' is not defined

In [ ]:
#47. Update middle row with 99.
arr[1:2,0:3]=99
print(arr)

[[ 3  2  1]
 [99 99 99]
 [ 9  8  7]]


In [ ]:
#48. Add 10 to all array elements.
print(arr+10)

[[ 13  12  11]
 [109 109 109]
 [ 19  18  17]]


In [ ]:
#49. Multiply all elements by 5.
print(arr*5)

[[ 15  10   5]
 [495 495 495]
 [ 45  40  35]]


In [ ]:
#50. Divide all elements by 2.
print(arr//2)

[[ 1  1  0]
 [49 49 49]
 [ 4  4  3]]


In [ ]:
#51. Find maximum value in array.
max_value=np.max(arr)
print(max_value)

9


In [ ]:
print(arr)

[[9 2 3]
 [2 9 5]
 [7 8 9]]


In [ ]:
#52. Find minimum value in array.
max_value=np.min(arr)
print(max_value)

2


In [ ]:
#53. Find index of maximum value.
i=np.argmax(arr)
print(i)

0


In [ ]:
#54. Find index of minimum value.
i=np.argmin(arr)
print(i)

1


In [ ]:
#55. Find sum of all elements.
t=0
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    t+=arr[i][j]


print(t)
print(arr)



54
[[9 2 3]
 [2 9 5]
 [7 8 9]]


In [27]:
#57. Find column-wise sum.

t=0
for i in range(arr.shape[1]):
  t+=arr[i]

print(t)

[18 19 17]


In [26]:
#56. Find row-wise sum.
row_sum = []
for i in range(arr.shape[0]):   # iterate over rows
    total = 0
    for j in range(arr.shape[1]):  # iterate over columns
        total += arr[i][j]
    row_sum.append(total)

print(row_sum)

[np.int64(14), np.int64(16), np.int64(24)]


In [28]:
#58. Find mean of array.
t=0
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    t+=arr[i][j]


print(t//len(arr))

18


In [29]:
len(arr)

3